---
author: Your Name
title: Project Dataset and Topics
output: html
---

[Link to dataset](ttps://api.petfinder.com/v2/animals)

Things you plan to investigate using this dataset:

- Find stats about adoptable cats such as totals and averages for color, type, ect
- create a dataframe of dogs and cats that I would adopt based on my requirments, maybe add images of them
- find if cats in the city are more likely to be house trained than non city cats

Stat 351 topics you plan to cover during the analysis:

1. API use
2. well chosen graphics
3. efficient data technique
4. polite technique 

---

Comments

- Efficient data technique? What does that mean, exactly?

- I think you're going to have trouble getting enough information from this site to demonstrate challenging topics. Your project may fall a bit flat as a result. This only has points -- so you're limited to scoring at best, which isn't much depth. 

- This isn't exactly "public agency/nonprofit" data as I'd envisioned it. 

I would suggest choosing a different topic with data that's going to require more than a quick grab from the webpage and a bit of string separation to format. I just don't think you're going to get enough out of this to stay busy for an hour. 
